spring.application.name=gestione-ticket

spring.datasource.url=jdbc:mysql://localhost:3306/gestioneticket
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate auto ddl
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG


spring.web.error.include-binding-errors=always
spring.web.error.include-message=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=TRACE


# --- Redis connection ---
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.repositories.enabled=false

# --- Spring Session su Redis ---
spring.session.store-type=redis
spring.session.redis.namespace=gestioneticket:sessions
# salva la sessione solo quando cambia
spring.session.redis.flush-mode=on_save
# TTL delle sessioni
server.servlet.session.timeout=30m

# --- Cookie di sessione (per ambienti HTTPS) ---
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax